[ADD] base_web_hook: Create abstract web hooks
OCA/webhook pull request #4
Opened 2017-10-10 21:13 UTC by lasley

* Create a module to allow for the receipt of web hooks in an abstract fashion

Depends:
- [ ] #3

2017-10-11 21:08 UTC, lasley commented on base_web_hook/controllers/main.py
> +        type='json',
Hmmmm maybe should be an HTTP receiver as well

2017-10-11 23:55 UTC, lasley commented
Alright this is implemented in a connector, so it's less rough around the edges now. We've still got some testing to do on the connector, and another one to implement, so I would assume there's still work to come here.

[This is an implementation example](https://github.com/LasLabs/odoo-connector-helpscout/pull/3)

2017-10-13 15:54 UTC, lasley commented on base_web_hook/models/web_hook.py
> +    name = fields.Char(
Add `UNIQUE(interface, name)`

2017-10-17 23:42 UTC, lasley commented
Alright I've now added a Request Bin hook type, which simply catches and saves inbound requests. This is a useful tool for testing web hooks as an administrator, but will also help me test the module in an automated fashion.

2017-11-28 17:48 UTC, hbrunn commented
late to the party, are you aware of https://github.com/OCA/server-tools/tree/10.0/webhook ?
(I do have a couple of things I'd like to change...)

2017-11-28 18:06 UTC, lasley commented
Not aware at all. How did you conquer the receipt of JSON?

2017-11-28 18:10 UTC, hbrunn commented
I didn't conquer anything there, didn't even use the module. But I read it yesterday and decided I can't use it for what I had in mind.

2017-11-28 18:13 UTC, hbrunn commented
looks straightforward enough: https://github.com/OCA/server-tools/blob/10.0/webhook/controllers/main.py#L17

2017-11-28 18:14 UTC, lasley commented
I'm looking at the module, and it definitely does not work as intended in all cases. The route is using `type='json'`, which means that the hook must be an RPC formatted request. See https://github.com/odoo/odoo/issues/7766

I would propose this module as a direct successor to the other TBH. There are significantly more features here, such as the ability to receive non-JSON requests & authenticated hooks.

2017-11-28 18:21 UTC, lasley commented
@moylop260 - your module https://github.com/OCA/server-tools/tree/10.0/webhook has instructions specifically for Github web hooks, but odoo/odoo#7766 alludes to the fact that this does not actual work. Can you confirm OCA/server-tools/webhook does work for any inbound JSON webhook without sitting a proxy in front of the Odoo server?

2018-05-08 08:02 UTC, pntabuye reviewed
tested on Odoo 10e and not conclusive. The non JSON-RPC json does not raise a BadRequest error from werkzeug.

2018-05-08 08:02 UTC, pntabuye commented on base_json_request/http.py
> +            args = self.httprequest.args
AttributeError: 'JsonRequest' object has no attribute 'httprequest'

2018-08-08 14:27 UTC, mlaitinen requested changes

2018-08-08 14:27 UTC, mlaitinen commented on base_json_request/README.rst
> +Bug Tracker
Please add a usage section on how to use this module

2018-08-08 14:27 UTC, mlaitinen commented on base_web_hook/README.rst
> +Bug Tracker
Please add a usage section on how to use this module

2024-07-29 13:34 UTC, gurneyalex commented
sale, old odoo running on python 2 -> closing

2024-07-29 13:34 UTC, closed without merging